services:
  node:
    build: .
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c 'cd react-app && npm run start'
    ports:
      - '3000:3000'
